# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_resturant_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resturant',
            new_name='Restaurant',
        ),
    ]
